spring:
  datasource:
    url: jdbc:mysql://localhost:3306/quiznews_db
    username: root
    password: '!Banana0320'
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect